databases:
  - name: postgres
    ipAllowList: []
    databaseName: 4Economy
    user: postgres

services:
  - type: web
    name: 4Economy
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false